### ISSUE TITLE
alexa snap fails to establish listening port

### ISSUE THREAD

**Issue by GaryGapinski** [devicehive/AlexaDevice#1]
Using alexa (beta) 1.1 from 'data-art' on Ubuntu 17.04 x86_64.

Using these snap install [instructions](https://insights.ubuntu.com/2017/05/16/dataart-release-new-version-of-alexa-virtual-device-for-raspberry-pi/), I received an info message during install, and saw no listening port 3000 subsequent to the install. I'm quite new at snap usage, so this may be an error on my part.
```
root@NUC7i7BNH:~# snap install --devmode pulseaudio
2017-05-22T00:29:20Z INFO cannot auto connect core:core-support-plug to core:core-support: (slot auto-connection), existing connection state "core:core-support-plug core:core-support" in the way
2017-05-22T00:29:22Z INFO cannot auto connect core:core-support-plug to core:core-support: (slot auto-connection), existing connection state "core:core-support-plug core:core-support" in the way
2017-05-22T00:29:25Z INFO cannot auto connect pulseaudio:client (plug auto-connection), candidates found: "core:pulseaudio, pulseaudio:service"
pulseaudio 8.0-3 from 'canonical' installed
root@NUC7i7BNH:~# snap install --channel beta alexa
2017-05-22T00:30:09Z INFO cannot auto connect alexa:pulseaudio (plug auto-connection), candidates found: "core:pulseaudio, pulseaudio:service"
alexa (beta) 1.1 from 'data-art' installed
root@NUC7i7BNH:~# netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 192.168.2.96:53         0.0.0.0:*               LISTEN      13732/named         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3770/sshd           
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      3263/cupsd          
tcp        0      0 127.0.0.1:32600         0.0.0.0:*               LISTEN      12346/Plex Tuner Se 
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN      13784/nxnode.bin    
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      13732/named         
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      3724/master         
tcp        0      0 0.0.0.0:4000            0.0.0.0:*               LISTEN      4026/nxd            
tcp        0      0 127.0.0.1:12001         0.0.0.0:*               LISTEN      13784/nxnode.bin    
tcp        0      0 0.0.0.0:1443            0.0.0.0:*               LISTEN      5553/vmware-hostd   
tcp        0      0 127.0.0.1:42661         0.0.0.0:*               LISTEN      12359/Plex Plug-in  
tcp        0      0 0.0.0.0:902             0.0.0.0:*               LISTEN      5303/vmware-authdla 
tcp        0      0 127.0.0.1:25001         0.0.0.0:*               LISTEN      13819/nxclient.bin  
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      3775/systemd-resolv 
tcp        0      0 127.0.0.1:20332         0.0.0.0:*               LISTEN      3790/nxserver.bin   
tcp        0      0 0.0.0.0:19150           0.0.0.0:*               LISTEN      4753/gkrellmd       
tcp        0      0 127.0.0.1:33263         0.0.0.0:*               LISTEN      12290/Plex Plug-in  
tcp        0      0 127.0.0.1:8307          0.0.0.0:*               LISTEN      5553/vmware-hostd   
tcp6       0      0 :::22                   :::*                    LISTEN      3770/sshd           
tcp6       0      0 ::1:631                 :::*                    LISTEN      3263/cupsd          
tcp6       0      0 ::1:7001                :::*                    LISTEN      13784/nxnode.bin    
tcp6       0      0 ::1:953                 :::*                    LISTEN      13732/named         
tcp6       0      0 :::25                   :::*                    LISTEN      3724/master         
tcp6       0      0 :::4000                 :::*                    LISTEN      4026/nxd            
tcp6       0      0 :::1443                 :::*                    LISTEN      5553/vmware-hostd   
tcp6       0      0 :::902                  :::*                    LISTEN      5303/vmware-authdla 
tcp6       0      0 :::5355                 :::*                    LISTEN      3775/systemd-resolv 
tcp6       0      0 :::19150                :::*                    LISTEN      4753/gkrellmd       
tcp6       0      0 :::32400                :::*                    LISTEN      12259/Plex Media Se 
tcp6       0      0 ::1:32401               :::*                    LISTEN      12259/Plex Media Se 
root@NUC7i7BNH:~# snap interfaces
Slot                      Plug
:account-control          -
:alsa                     -
:autopilot-introspection  -
:avahi-observe            -
:bluetooth-control        -
:browser-support          -
:camera                   -
:classic-support          -
:core-support             core:core-support-plug
:cups-control             -
:dcdbas-control           -
:docker-support           -
:firewall-control         -
:framebuffer              -
:fuse-support             -
:gsettings                -
:hardware-observe         -
:home                     pulseaudio
:io-ports-control         -
:joystick                 -
:kernel-module-control    -
:kubernetes-support       -
:libvirt                  -
:locale-control           -
:log-observe              -
:lxd-support              -
:modem-manager            -
:mount-observe            -
:network                  alexa,pulseaudio
:network-bind             alexa
:network-control          -
:network-manager          -
:network-observe          -
:network-setup-control    -
:network-setup-observe    -
:ofono                    -
:opengl                   -
:openvswitch              -
:openvswitch-support      -
:optical-drive            -
:physical-memory-control  -
:physical-memory-observe  -
:ppp                      -
:process-control          -
:pulseaudio               -
:raw-usb                  -
:removable-media          -
:screen-inhibit-control   -
:shutdown                 -
:snapd-control            -
:system-observe           -
:system-trace             -
:time-control             -
:timeserver-control       -
:timezone-control         -
:tpm                      -
:uhid                     -
:unity7                   -
:upower-observe           -
:x11                      -
pulseaudio:service        pulseaudio:client
-                         alexa:pulseaudio
root@NUC7i7BNH:~# snap run alexa
xcb_connection_has_error() returned true
shm_open() failed: Permission denied
Failed to create secure directory (/run/user/0/snap.alexa/pulse): No such file or directory
Traceback (most recent call last):
  File "/snap/alexa/2/bin/alexa.py", line 20, in <module>
    main()
  File "/snap/alexa/2/bin/alexa.py", line 10, in main
    alexa_audio_device.init()
  File "/snap/alexa/2/bin/alexa_audio_device_pulse.py", line 29, in init
    + str(pa.strerror(error), 'ascii'))
Exception: Could not create pulse audio output stream: No such device or address
root@NUC7i7BNH:~# mount|grep shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
root@NUC7i7BNH:~# 
```

**Comment by Narvey** [comment]
I have the same problem. Even when installing the old way without the snap, I still get "Could not create pulse audio output stream: No such device or address" when running `python3 alexa.py`.

Unfortunately, there isn't a whole lot of info on the nature of the problem. What address did the script try to access (so maybe I can try to access it from outside the application and see if that works)? Is it a permissions problem (running as root didn't help)?

**Comment by minomit** [comment]
same problem

**Comment by jcrollard84** [comment]
Same issue. Pulseaudio is installed by default. Anyone fix this?

**Comment by MaveriQ** [comment]
.. 3 years later ..

same problem!
